-- =============================================================================
-- SIMULATION ISOLATION — Data Layer (Write-Path Only)
-- Migration: 20260506160000_simulation_isolation
--
-- STEP 1: Add `is_simulated` boolean column (default FALSE) to:
--   - validation_signals
--   - delivery_attempts
--   - activity_logs
--
-- STEP 2: Add partial indexes on real (non-simulated) rows only:
--   - validation_signals(place_id) WHERE is_simulated = FALSE
--   - delivery_attempts(place_id)  WHERE is_simulated = FALSE
--
-- CONSTRAINTS:
--   - No existing data is touched (ALTER TABLE … DEFAULT FALSE is safe)
--   - No read/query path changes
--   - Fully idempotent via IF NOT EXISTS / conditional DDL
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. validation_signals
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.validation_signals
    ADD COLUMN IF NOT EXISTS is_simulated BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.validation_signals.is_simulated
    IS 'TRUE when this signal was generated by a simulation run (x-simulation: true header). Never written in production.';

-- Partial index: production queries only ever touch is_simulated = FALSE rows.
-- This index is intentionally partial so simulation data does not pollute
-- query plans, cardinality estimates, or live scoring paths.
CREATE INDEX IF NOT EXISTS idx_validation_signals_place_id_real
    ON public.validation_signals(place_id)
    WHERE is_simulated = FALSE;


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. delivery_attempts
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.delivery_attempts
    ADD COLUMN IF NOT EXISTS is_simulated BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.delivery_attempts.is_simulated
    IS 'TRUE when this delivery attempt was generated by a simulation run (x-simulation: true header). Never written in production.';

-- Partial index: mirrors the one on validation_signals for consistent
-- query plans across the delivery feedback pipeline.
CREATE INDEX IF NOT EXISTS idx_delivery_attempts_place_id_real
    ON public.delivery_attempts(place_id)
    WHERE is_simulated = FALSE;


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. activity_logs
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.activity_logs
    ADD COLUMN IF NOT EXISTS is_simulated BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.activity_logs.is_simulated
    IS 'TRUE when this log entry was generated by a simulation run (x-simulation: true header). Never written in production.';

-- Note: No partial index on activity_logs(place_id) — the existing
-- idx_activity_logs_place_id already covers real-time feed queries.
-- Adding a simulation flag here is write-path only; read path unchanged.


-- =============================================================================
-- END OF MIGRATION
-- =============================================================================
